controller_manager:
  ros__parameters:
    update_rate: 100  # H

    centauri_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    centauri_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

centauri_arm_controller:
  ros__parameters:  
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - 'joint1'
      - 'joint2'
      - 'joint3'
      - 'joint4'
      - 'joint5'
      - 'joint6'

centauri_hand_controller:
  ros__parameters:
    joint: joint_gear1